CREATE TABLE IF NOT EXISTS assignment (
  id VARCHAR(255) UNIQUE,
  creator VARCHAR(255) DEFAULT NULL,
  title VARCHAR(255) DEFAULT NULL,
  duration INTEGER DEFAULT NULL,
  topic VARCHAR(255) DEFAULT NULL,
  difficulty VARCHAR(255) DEFAULT NULL
);